SELECT AVG(t.NewAccounts) AS Average FROM 
(	
	SELECT 
		COUNT(DISTINCT SRC_ACCT_ID) AS NewAccounts, 
		CONVERT(VARCHAR, DATA_LOAD_DTTM, 1) AS LoadDay
	FROM 
		dwadm2.CD_ACCT 
	WHERE 
		DATA_LOAD_DTTM 
			BETWEEN 
				GETDATE()-5 AND GETDATE()
	GROUP BY CONVERT(VARCHAR, DATA_LOAD_DTTM, 1) 
) AS t


SELECT  * FROM dwadm2.CF_BILLED_USAGE WHERE CONVERT(VARCHAR, UDDGEN1, 1) = '12/27/21' and DATA_LOAD_DTTM BETWEEN GETDATE()-8 AND GETDATE()

SELECT 
	COUNT(DISTINCT SRC_BILL_ID) DwCount, 
	CONVERT(VARCHAR, DATA_LOAD_DTTM, 1) DATA_LOAD_DTTM ,
	FORMAT(DATA_LOAD_DTTM, 'dddd') as DayofWeek
FROM 
	[dwadm2].[CF_BILLED_USAGE]
WHERE 
	DATA_LOAD_DTTM BETWEEN GETDATE()-5 AND GETDATE()
GROUP BY
	CONVERT(VARCHAR, DATA_LOAD_DTTM, 1) , FORMAT(DATA_LOAD_DTTM, 'dddd')
order by DATA_LOAD_DTTM desc




---------------------------------


SELECT CONVERT(VARCHAR,GETDATE(),1)

SELECT SRC_ACCT_ID, COUNT(ACCT_KEY) AS COUNT_ACCT 
FROM dwadm2.CD_ACCT 
WHERE (DATA_LOAD_DTTM BETWEEN '2021-12-20 12:00' AND '2021-12-29 12:00')  AND EFF_END_DTTM = '3000-12-31'
GROUP BY SRC_ACCT_ID


order by SRC_ACCT_ID DESC
AND 
EFF_END_DTTM = '3000-12-31'

(CONVERT(VARCHAR, EFF_START_DTTM ,1) = CONVERT(VARCHAR, DATA_LOAD_DTTM ,1))

SELECT * FROM dwadm2.CD_ACCT WHERE SRC_ACCT_ID LIKE '2198033276' ORDER BY ACCT_KEY
AND 
EFF_END_DTTM = '3000-12-31'

----------------------------------------------------------------

SELECT 
	COUNT(DISTINCT SRC_ACCT_ID) DwCount, 
	CONVERT(VARCHAR, DATA_LOAD_DTTM, 1) DATA_LOAD_DTTM ,
	FORMAT(DATA_LOAD_DTTM, 'dddd') as DayofWeek
FROM 
	dwadm2.CD_ACCT
WHERE 
	DATA_LOAD_DTTM BETWEEN GETDATE()-360 AND GETDATE()
GROUP BY
	CONVERT(VARCHAR, DATA_LOAD_DTTM, 1) , FORMAT(DATA_LOAD_DTTM, 'dddd')
ORDER BY DwCount DESC